name: Bump Orbs
author: "Edd Steel <edd@eddsteel.com>"
description: "Update the supplied Circle CI configuration to use the latest version of its orbs."
inputs:
  config:
    description: Relative path to Circle CI configuration file
    required: false
    default: .circleci/config.yml
  token:
    description: Circle CI token (required if private orbs are involved)
    required: false
  ignore:
    description: A newline separated list of orbs to ignore updates for
    required: false
outputs:
  summary:
    description: List of updates in markdown format
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
    - ${{ inputs.token }}
    - ${{ inputs.ignore }}
branding:
  icon: circle
  color: green
